import { NextResponse } from 'next/server';
import { getAdminSession } from '@/lib/auth';
import { getAdminOverviewStats } from '@/lib/admin-overview';
import { createWorkbookXlsx } from '@/lib/xlsx';

export const dynamic = 'force-dynamic';

function formatDate(value: Date | null) {
  return value ? value.toLocaleString() : '—';
}

export async function GET() {
  try {
    const admin = await getAdminSession();
    if (!admin) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const stats = await getAdminOverviewStats();
    const generatedAt = new Date();

    const workbook = createWorkbookXlsx([
      {
        name: 'Overview',
        rows: [
          ['EDSA Admin Overview Export'],
          ['Generated at', generatedAt.toLocaleString()],
          ['Generated by', admin.email],
          [],
          ['Metric', 'Value'],
          ['Total Reports', stats.totalReports],
          ['Active Hazards', stats.totalHazards],
          ['Power On Areas', stats.areaSummary.filter((area) => area.status === 'on').length],
          ['Outage Areas', stats.areaSummary.filter((area) => area.status === 'out').length],
          ['Unknown Areas', stats.areaSummary.filter((area) => area.status === 'unknown').length],
        ],
      },
      {
        name: 'Area Summary',
        rows: [
          ['Area', 'Status', 'Reports', 'Confidence (%)', 'Last Updated'],
          ...stats.areaSummary.map((area) => [
            area.name,
            area.status.toUpperCase(),
            area.reportCount,
            area.confidence,
            formatDate(area.lastUpdated),
          ]),
        ],
      },
      {
        name: 'Hazards',
        rows: [
          ['Type', 'Area', 'Community', 'Street Name', 'House Number', 'Description', 'Coordinates', 'Reported At'],
          ...stats.recentHazards.map((hazard) => [
            hazard.type,
            hazard.area,
            hazard.areaName || '—',
            hazard.streetName || '—',
            hazard.houseNumber || '—',
            hazard.description || '—',
            hazard.lat !== null && hazard.lng !== null ? `${hazard.lat.toFixed(5)}, ${hazard.lng.toFixed(5)}` : '—',
            formatDate(hazard.reportedAt),
          ]),
        ],
      },
      {
        name: 'Reports',
        rows: [
          ['Area', 'Status', 'Reported At', 'Device', 'Coordinates'],
          ...stats.recentReports.map((report) => [
            report.area,
            report.status.toUpperCase(),
            formatDate(report.reportedAt),
            report.deviceId || 'Anonymous',
            report.reporterLat !== null && report.reporterLng !== null
              ? `${report.reporterLat.toFixed(5)}, ${report.reporterLng.toFixed(5)}`
              : '—',
          ]),
        ],
      },
    ], generatedAt);

    return new NextResponse(workbook, {
      status: 200,
      headers: {
        'Content-Type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'Content-Disposition': `attachment; filename="edsa-admin-overview-${generatedAt.toISOString().slice(0, 10)}.xlsx"`,
        'Cache-Control': 'no-store',
      },
    });
  } catch (error) {
    console.error('GET /api/admin/export error:', error);
    return NextResponse.json({ error: 'Failed to export admin overview.' }, { status: 500 });
  }
}
